# Generated by Django 3.0.8 on 2020-08-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('name', models.CharField(max_length=225, verbose_name='Company Name')),
                ('code', models.CharField(max_length=10, verbose_name='Company Code')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'InActive'), ('REGISTERED', 'Registered')], max_length=10, verbose_name='Company Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=2, verbose_name='Gender')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'InActive')], max_length=10, verbose_name='Account Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompanyModel', verbose_name='Company')),
            ],
            options={
                'unique_together': {('company', 'email')},
            },
        ),
    ]
